version: '3'
services:
  atcoder_automation:
    build:
     context: ./
     dockerfile: Dockerfile
    command: jupyter notebook --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8888 --NotebookApp.token='' --allow-root
    volumes:
      - ./app:/app
      - ./notebooks:/opt/notebooks
    restart: unless-stopped
    ports:
      - 8888:8888
    #tty: true