version: '3.5'

services:
  pg:
    container_name: pg
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
      POSTGRES_DB: sandbox
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
       - ./postgres:/data/postgres
       - ./postgres:/var/lib/postgresql
       - $PWD/docker/db/init:/docker-entrypoint-initdb.d
    ports:
      - "25432:5432"
      - "20024:20022"
    restart: unless-stopped
    networks:
      local:
networks:
  local:
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 172.31.0.0/24