override CC := /usr/local/bin/g++
CFLAGS := -std=c++11

a:
	$(CC) -o a.out $(CFLAGS) a.cpp
b: 
	$(CC) -o b.out $(CFLAGS) b.cpp
c:
	$(CC) -o c.out $(CFLAGS) c.cpp
d: 
	$(CC) -o d.out $(CFLAGS) d.cpp 
e:
	$(CC) -o e.out $(CFLAGS) e.cpp
f: 
	$(CC) -o f.out $(CFLAGS) f.cpp
cpa:
	cp template.cpp a.cpp
cpb:
	cp template.cpp b.cpp
cpc:
	cp template.cpp c.cpp
cpd:
	cp template.cpp d.cpp
cpe:
	cp template.cpp e.cpp
cpf:
	cp template.cpp f.cpp
exa:
	./a.out
exb:
	./b.out
exc:
	./c.out
exd:
	./d.out
exe:
	./e.out
exf:
	./f.out
clean:
	$(RM) *.out